# Generated by Django 2.0.7 on 2019-08-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20190805_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='correo',
            field=models.CharField(max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='identificacion',
            field=models.CharField(max_length=50, null=True, verbose_name='Identificación'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], default='femenino', max_length=20, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=100, null=True, verbose_name='Teléfono'),
        ),
    ]
