# Generated by Django 2.0.7 on 2019-08-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizada', 'Finalizada'), ('anulada', 'Anulada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cita',
            name='horario',
            field=models.CharField(choices=[('turno_1', '8:00 - 9:00'), ('turno_2', '9:00 - 10:00'), ('turno_3', '10:00 - 11:00'), ('turno_4', '11:00 - 12:00'), ('turno_5', '12:00 - 13:00'), ('turno_6', '13:00 - 14:00'), ('turno_7', '14:00 - 15:00'), ('turno_8', '15:00 - 16:00'), ('turno_9', ' 16:00 - 17:00'), ('turno_10', '17:00 - 18:00'), ('turno_11', '18:00 - 19:00'), ('turno_12', '19:00 - 20:00'), ('turno_13', '20:00 - 21:00'), ('turno_14', ' 21:00 - 22:00')], default='Seleccionar', max_length=20, verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
